#### Write a function so that the columns of the output matrix are powers of the input vector

In [1]:
import numpy as np
np.vander([1, 2, 3, 4])

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [2]:
import numpy as np
def Vander(inp_list, N=None, increasing = False):
    
    if N == None :
        N = len(inp_list)
    if increasing:
        matrix = [[element**power for power in range(0, N)] for element in inp_list]
        print(np.row_stack(matrix))
    else:
        matrix = [[element**power for power in range(N-1, -1, -1)] for element in inp_list]
        print(np.row_stack(matrix))
        
Vander([1, 2, 3, 4])

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]]


#### Write a function to find moving average in an array over a window: Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [24]:
my_list=[3,5,7,2,8,10,11,65,72,81,99,100,150]
window_size = 3
iterations=len(my_list) - window_size + 1
i = 0
Output=[]
for i in range(iterations):
    this_window = my_list[i : i + window_size]

    moving_averages = sum(this_window) / window_size
    Output.append(moving_averages)
    i += 1

print(Output)


[5.0, 4.666666666666667, 5.666666666666667, 6.666666666666667, 9.666666666666666, 28.666666666666668, 49.333333333333336, 72.66666666666667, 84.0, 93.33333333333333, 116.33333333333333]
